replicaCount: 1
name: jenkins-demo
namespace: demo
image:
  repository: fra.ocir.io/fromv4diycqh/quistoropn/demo/docker
  pullPolicy: Always
  tag: 1.1.1
service:
  enabled: true
  type: LoadBalancer
  ports:
    app:
      port: 8080
      targetPort: 8080
      protocol: TCP
